/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAccountantRouteImport } from './routes/_authenticated/accountant'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedBuyerRouteImport } from './routes/_authenticated/buyer'
import { Route as AuthenticatedCardsRouteImport } from './routes/_authenticated/cards'
import { Route as AuthenticatedCollectRouteImport } from './routes/_authenticated/collect'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedDeviceCheckRouteImport } from './routes/_authenticated/device-check'
import { Route as AuthenticatedFarmerRouteImport } from './routes/_authenticated/farmer'
import { Route as AuthenticatedFieldSetupRouteImport } from './routes/_authenticated/field-setup'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedForbiddenRouteImport } from './routes/_authenticated/forbidden'
import { Route as AuthenticatedHandoverRouteImport } from './routes/_authenticated/handover'
import { Route as AuthenticatedHandoversRouteImport } from './routes/_authenticated/handovers'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthenticatedQualityRouteImport } from './routes/_authenticated/quality'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRouteMarkingRouteImport } from './routes/_authenticated/route-marking'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as AuthenticatedTripRouteImport } from './routes/_authenticated/trip'
import { Route as AuthenticatedCardCodeRouteImport } from './routes/_authenticated/card.$code'
import { Route as AuthenticatedHandoverTripidRouteImport } from './routes/_authenticated/handover.$tripid'
import { Route as AuthenticatedTripHistoryTripidRouteImport } from './routes/_authenticated/trip-history.$tripid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountantRoute = AuthenticatedAccountantRouteImport.update({
  id: '/accountant',
  path: '/accountant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyerRoute = AuthenticatedBuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCardsRoute = AuthenticatedCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectRoute = AuthenticatedCollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeviceCheckRoute =
  AuthenticatedDeviceCheckRouteImport.update({
    id: '/device-check',
    path: '/device-check',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFarmerRoute = AuthenticatedFarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFieldSetupRoute = AuthenticatedFieldSetupRouteImport.update({
  id: '/field-setup',
  path: '/field-setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForbiddenRoute = AuthenticatedForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHandoverRoute = AuthenticatedHandoverRouteImport.update({
  id: '/handover',
  path: '/handover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHandoversRoute = AuthenticatedHandoversRouteImport.update({
  id: '/handovers',
  path: '/handovers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQualityRoute = AuthenticatedQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRouteMarkingRoute =
  AuthenticatedRouteMarkingRouteImport.update({
    id: '/route-marking',
    path: '/route-marking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripRoute = AuthenticatedTripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCardCodeRoute = AuthenticatedCardCodeRouteImport.update({
  id: '/card/$code',
  path: '/card/$code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHandoverTripidRoute =
  AuthenticatedHandoverTripidRouteImport.update({
    id: '/$tripid',
    path: '/$tripid',
    getParentRoute: () => AuthenticatedHandoverRoute,
  } as any)
const AuthenticatedTripHistoryTripidRoute =
  AuthenticatedTripHistoryTripidRouteImport.update({
    id: '/trip-history/$tripid',
    path: '/trip-history/$tripid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accountant': typeof AuthenticatedAccountantRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/buyer': typeof AuthenticatedBuyerRoute
  '/cards': typeof AuthenticatedCardsRoute
  '/collect': typeof AuthenticatedCollectRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/device-check': typeof AuthenticatedDeviceCheckRoute
  '/farmer': typeof AuthenticatedFarmerRoute
  '/field-setup': typeof AuthenticatedFieldSetupRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/handover': typeof AuthenticatedHandoverRouteWithChildren
  '/handovers': typeof AuthenticatedHandoversRoute
  '/live': typeof AuthenticatedLiveRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/route-marking': typeof AuthenticatedRouteMarkingRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/trip': typeof AuthenticatedTripRoute
  '/card/$code': typeof AuthenticatedCardCodeRoute
  '/handover/$tripid': typeof AuthenticatedHandoverTripidRoute
  '/trip-history/$tripid': typeof AuthenticatedTripHistoryTripidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accountant': typeof AuthenticatedAccountantRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/buyer': typeof AuthenticatedBuyerRoute
  '/cards': typeof AuthenticatedCardsRoute
  '/collect': typeof AuthenticatedCollectRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/device-check': typeof AuthenticatedDeviceCheckRoute
  '/farmer': typeof AuthenticatedFarmerRoute
  '/field-setup': typeof AuthenticatedFieldSetupRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/handover': typeof AuthenticatedHandoverRouteWithChildren
  '/handovers': typeof AuthenticatedHandoversRoute
  '/live': typeof AuthenticatedLiveRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/route-marking': typeof AuthenticatedRouteMarkingRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/trip': typeof AuthenticatedTripRoute
  '/card/$code': typeof AuthenticatedCardCodeRoute
  '/handover/$tripid': typeof AuthenticatedHandoverTripidRoute
  '/trip-history/$tripid': typeof AuthenticatedTripHistoryTripidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accountant': typeof AuthenticatedAccountantRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/buyer': typeof AuthenticatedBuyerRoute
  '/_authenticated/cards': typeof AuthenticatedCardsRoute
  '/_authenticated/collect': typeof AuthenticatedCollectRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/device-check': typeof AuthenticatedDeviceCheckRoute
  '/_authenticated/farmer': typeof AuthenticatedFarmerRoute
  '/_authenticated/field-setup': typeof AuthenticatedFieldSetupRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/forbidden': typeof AuthenticatedForbiddenRoute
  '/_authenticated/handover': typeof AuthenticatedHandoverRouteWithChildren
  '/_authenticated/handovers': typeof AuthenticatedHandoversRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/_authenticated/quality': typeof AuthenticatedQualityRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/route-marking': typeof AuthenticatedRouteMarkingRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/_authenticated/trip': typeof AuthenticatedTripRoute
  '/_authenticated/card/$code': typeof AuthenticatedCardCodeRoute
  '/_authenticated/handover/$tripid': typeof AuthenticatedHandoverTripidRoute
  '/_authenticated/trip-history/$tripid': typeof AuthenticatedTripHistoryTripidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accountant'
    | '/agent'
    | '/buyer'
    | '/cards'
    | '/collect'
    | '/collections'
    | '/device-check'
    | '/farmer'
    | '/field-setup'
    | '/finance'
    | '/forbidden'
    | '/handover'
    | '/handovers'
    | '/live'
    | '/manager'
    | '/owner'
    | '/quality'
    | '/reports'
    | '/route-marking'
    | '/transfers'
    | '/trip'
    | '/card/$code'
    | '/handover/$tripid'
    | '/trip-history/$tripid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accountant'
    | '/agent'
    | '/buyer'
    | '/cards'
    | '/collect'
    | '/collections'
    | '/device-check'
    | '/farmer'
    | '/field-setup'
    | '/finance'
    | '/forbidden'
    | '/handover'
    | '/handovers'
    | '/live'
    | '/manager'
    | '/owner'
    | '/quality'
    | '/reports'
    | '/route-marking'
    | '/transfers'
    | '/trip'
    | '/card/$code'
    | '/handover/$tripid'
    | '/trip-history/$tripid'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accountant'
    | '/_authenticated/agent'
    | '/_authenticated/buyer'
    | '/_authenticated/cards'
    | '/_authenticated/collect'
    | '/_authenticated/collections'
    | '/_authenticated/device-check'
    | '/_authenticated/farmer'
    | '/_authenticated/field-setup'
    | '/_authenticated/finance'
    | '/_authenticated/forbidden'
    | '/_authenticated/handover'
    | '/_authenticated/handovers'
    | '/_authenticated/live'
    | '/_authenticated/manager'
    | '/_authenticated/owner'
    | '/_authenticated/quality'
    | '/_authenticated/reports'
    | '/_authenticated/route-marking'
    | '/_authenticated/transfers'
    | '/_authenticated/trip'
    | '/_authenticated/card/$code'
    | '/_authenticated/handover/$tripid'
    | '/_authenticated/trip-history/$tripid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accountant': {
      id: '/_authenticated/accountant'
      path: '/accountant'
      fullPath: '/accountant'
      preLoaderRoute: typeof AuthenticatedAccountantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyer': {
      id: '/_authenticated/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof AuthenticatedBuyerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cards': {
      id: '/_authenticated/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AuthenticatedCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collect': {
      id: '/_authenticated/collect'
      path: '/collect'
      fullPath: '/collect'
      preLoaderRoute: typeof AuthenticatedCollectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/device-check': {
      id: '/_authenticated/device-check'
      path: '/device-check'
      fullPath: '/device-check'
      preLoaderRoute: typeof AuthenticatedDeviceCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farmer': {
      id: '/_authenticated/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof AuthenticatedFarmerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field-setup': {
      id: '/_authenticated/field-setup'
      path: '/field-setup'
      fullPath: '/field-setup'
      preLoaderRoute: typeof AuthenticatedFieldSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forbidden': {
      id: '/_authenticated/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof AuthenticatedForbiddenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/handover': {
      id: '/_authenticated/handover'
      path: '/handover'
      fullPath: '/handover'
      preLoaderRoute: typeof AuthenticatedHandoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/handovers': {
      id: '/_authenticated/handovers'
      path: '/handovers'
      fullPath: '/handovers'
      preLoaderRoute: typeof AuthenticatedHandoversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quality': {
      id: '/_authenticated/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AuthenticatedQualityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/route-marking': {
      id: '/_authenticated/route-marking'
      path: '/route-marking'
      fullPath: '/route-marking'
      preLoaderRoute: typeof AuthenticatedRouteMarkingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trip': {
      id: '/_authenticated/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof AuthenticatedTripRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/card/$code': {
      id: '/_authenticated/card/$code'
      path: '/card/$code'
      fullPath: '/card/$code'
      preLoaderRoute: typeof AuthenticatedCardCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/handover/$tripid': {
      id: '/_authenticated/handover/$tripid'
      path: '/$tripid'
      fullPath: '/handover/$tripid'
      preLoaderRoute: typeof AuthenticatedHandoverTripidRouteImport
      parentRoute: typeof AuthenticatedHandoverRoute
    }
    '/_authenticated/trip-history/$tripid': {
      id: '/_authenticated/trip-history/$tripid'
      path: '/trip-history/$tripid'
      fullPath: '/trip-history/$tripid'
      preLoaderRoute: typeof AuthenticatedTripHistoryTripidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedHandoverRouteChildren {
  AuthenticatedHandoverTripidRoute: typeof AuthenticatedHandoverTripidRoute
}

const AuthenticatedHandoverRouteChildren: AuthenticatedHandoverRouteChildren = {
  AuthenticatedHandoverTripidRoute: AuthenticatedHandoverTripidRoute,
}

const AuthenticatedHandoverRouteWithChildren =
  AuthenticatedHandoverRoute._addFileChildren(
    AuthenticatedHandoverRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountantRoute: typeof AuthenticatedAccountantRoute
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedBuyerRoute: typeof AuthenticatedBuyerRoute
  AuthenticatedCardsRoute: typeof AuthenticatedCardsRoute
  AuthenticatedCollectRoute: typeof AuthenticatedCollectRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedDeviceCheckRoute: typeof AuthenticatedDeviceCheckRoute
  AuthenticatedFarmerRoute: typeof AuthenticatedFarmerRoute
  AuthenticatedFieldSetupRoute: typeof AuthenticatedFieldSetupRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedForbiddenRoute: typeof AuthenticatedForbiddenRoute
  AuthenticatedHandoverRoute: typeof AuthenticatedHandoverRouteWithChildren
  AuthenticatedHandoversRoute: typeof AuthenticatedHandoversRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRoute
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
  AuthenticatedQualityRoute: typeof AuthenticatedQualityRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRouteMarkingRoute: typeof AuthenticatedRouteMarkingRoute
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
  AuthenticatedTripRoute: typeof AuthenticatedTripRoute
  AuthenticatedCardCodeRoute: typeof AuthenticatedCardCodeRoute
  AuthenticatedTripHistoryTripidRoute: typeof AuthenticatedTripHistoryTripidRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountantRoute: AuthenticatedAccountantRoute,
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedBuyerRoute: AuthenticatedBuyerRoute,
  AuthenticatedCardsRoute: AuthenticatedCardsRoute,
  AuthenticatedCollectRoute: AuthenticatedCollectRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedDeviceCheckRoute: AuthenticatedDeviceCheckRoute,
  AuthenticatedFarmerRoute: AuthenticatedFarmerRoute,
  AuthenticatedFieldSetupRoute: AuthenticatedFieldSetupRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedForbiddenRoute: AuthenticatedForbiddenRoute,
  AuthenticatedHandoverRoute: AuthenticatedHandoverRouteWithChildren,
  AuthenticatedHandoversRoute: AuthenticatedHandoversRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRoute,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
  AuthenticatedQualityRoute: AuthenticatedQualityRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRouteMarkingRoute: AuthenticatedRouteMarkingRoute,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
  AuthenticatedTripRoute: AuthenticatedTripRoute,
  AuthenticatedCardCodeRoute: AuthenticatedCardCodeRoute,
  AuthenticatedTripHistoryTripidRoute: AuthenticatedTripHistoryTripidRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
